#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t start"

$L "____  _  ____  ____";
$L "|__|  |  |     |__|";
$L "|  |  |  |___  |      C  U  S  T  O  M    R  O  M";
$L "Welcome to Android `getprop ro.build.version.release` / AICP-`getprop ro.aicp.version`";
