PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/a6000.mk \
    $(LOCAL_DIR)/A6020.mk \
    $(LOCAL_DIR)/amami.mk \
    $(LOCAL_DIR)/angler.mk \
    $(LOCAL_DIR)/armani.mk \
    $(LOCAL_DIR)/athene.mk \
    $(LOCAL_DIR)/axon7.mk \
    $(LOCAL_DIR)/bacon.mk \
    $(LOCAL_DIR)/bullhead.mk \
    $(LOCAL_DIR)/cancro.mk \
    $(LOCAL_DIR)/cedric.mk \
    $(LOCAL_DIR)/chagalllte.mk \
    $(LOCAL_DIR)/chagallwifi.mk \
    $(LOCAL_DIR)/clark.mk \
    $(LOCAL_DIR)/condor.mk \
    $(LOCAL_DIR)/d2att.mk \
    $(LOCAL_DIR)/d2tmo.mk \
    $(LOCAL_DIR)/d2vzw.mk \
    $(LOCAL_DIR)/d2usc.mk \
    $(LOCAL_DIR)/d800.mk \
    $(LOCAL_DIR)/d801.mk \
    $(LOCAL_DIR)/d802.mk \
    $(LOCAL_DIR)/dior.mk \
    $(LOCAL_DIR)/e980.mk \
    $(LOCAL_DIR)/endeavoru.mk \
    $(LOCAL_DIR)/ether.mk \
    $(LOCAL_DIR)/falcon.mk \
    $(LOCAL_DIR)/ferrari.mk \
    $(LOCAL_DIR)/flounder.mk \
    $(LOCAL_DIR)/fugu.mk \
    $(LOCAL_DIR)/g2m.mk \
    $(LOCAL_DIR)/geehrc.mk \
    $(LOCAL_DIR)/gemini.mk \
    $(LOCAL_DIR)/griffin.mk \
    $(LOCAL_DIR)/grouper.mk \
    $(LOCAL_DIR)/gts210vewifi.mk \
    $(LOCAL_DIR)/h811.mk \
    $(LOCAL_DIR)/h815.mk \
    $(LOCAL_DIR)/h918.mk \
    $(LOCAL_DIR)/hammerhead.mk \
    $(LOCAL_DIR)/hammerheadcaf.mk \
    $(LOCAL_DIR)/himaul.mk \
    $(LOCAL_DIR)/hltetmo.mk \
    $(LOCAL_DIR)/honami.mk \
    $(LOCAL_DIR)/huashan.mk \
    $(LOCAL_DIR)/hydrogen.mk \
    $(LOCAL_DIR)/i9300.mk \
    $(LOCAL_DIR)/i9305.mk \
    $(LOCAL_DIR)/jewel.mk \
    $(LOCAL_DIR)/jfltecri.mk \
    $(LOCAL_DIR)/jfltecsp.mk \
    $(LOCAL_DIR)/jfltespr.mk \
    $(LOCAL_DIR)/jfltetmo.mk \
    $(LOCAL_DIR)/jflteusc.mk \
    $(LOCAL_DIR)/jfltevzw.mk \
    $(LOCAL_DIR)/jfltexx.mk \
    $(LOCAL_DIR)/kenzo.mk \
    $(LOCAL_DIR)/kiwi.mk \
    $(LOCAL_DIR)/klimtlte.mk \
    $(LOCAL_DIR)/kltekdi.mk \
    $(LOCAL_DIR)/klimtwifi.mk \
    $(LOCAL_DIR)/l01f.mk \
    $(LOCAL_DIR)/libra.mk \
    $(LOCAL_DIR)/ls980.mk \
    $(LOCAL_DIR)/lettuce.mk \
    $(LOCAL_DIR)/lux.mk \
    $(LOCAL_DIR)/m7.mk \
    $(LOCAL_DIR)/m7spr.mk \
    $(LOCAL_DIR)/m7vzw.mk \
    $(LOCAL_DIR)/mako.mk \
    $(LOCAL_DIR)/manta.mk \
    $(LOCAL_DIR)/marlin.mk \
    $(LOCAL_DIR)/mido.mk \
    $(LOCAL_DIR)/n1awifi.mk \
    $(LOCAL_DIR)/nicki.mk \
    $(LOCAL_DIR)/oneplus2.mk \
    $(LOCAL_DIR)/oneplus3.mk \
    $(LOCAL_DIR)/oneplus3t.mk \
    $(LOCAL_DIR)/osprey.mk \
    $(LOCAL_DIR)/otus.mk \
    $(LOCAL_DIR)/onyx.mk \
    $(LOCAL_DIR)/p2a42.mk \
    $(LOCAL_DIR)/peach.mk \
    $(LOCAL_DIR)/pme.mk \
    $(LOCAL_DIR)/peregrine.mk \
    $(LOCAL_DIR)/potter.mk \
    $(LOCAL_DIR)/s2.mk \
    $(LOCAL_DIR)/seed.mk \
    $(LOCAL_DIR)/serranodsdd.mk \
    $(LOCAL_DIR)/shamu.mk \
    $(LOCAL_DIR)/shamrock.mk \
    $(LOCAL_DIR)/shieldtablet.mk \
    $(LOCAL_DIR)/sprout4.mk \
    $(LOCAL_DIR)/surnia.mk \
    $(LOCAL_DIR)/T00F.mk \
    $(LOCAL_DIR)/thea.mk \
    $(LOCAL_DIR)/t0lte.mk \
    $(LOCAL_DIR)/tomato.mk \
    $(LOCAL_DIR)/trltespr.mk \
    $(LOCAL_DIR)/trltetmo.mk \
    $(LOCAL_DIR)/trltevzw.mk \
    $(LOCAL_DIR)/trltexx.mk \
    $(LOCAL_DIR)/tilapia.mk \
    $(LOCAL_DIR)/titan.mk \
    $(LOCAL_DIR)/togari.mk \
    $(LOCAL_DIR)/v500.mk \
    $(LOCAL_DIR)/victara.mk \
    $(LOCAL_DIR)/vs920.mk \
    $(LOCAL_DIR)/vs980.mk \
    $(LOCAL_DIR)/vs985.mk \
    $(LOCAL_DIR)/w7.mk \
    $(LOCAL_DIR)/wt88047.mk \
    $(LOCAL_DIR)/wx_na_wf.mk \
    $(LOCAL_DIR)/xt1053.mk \
    $(LOCAL_DIR)/xt1060.mk \
    $(LOCAL_DIR)/Z008.mk \
    $(LOCAL_DIR)/Z00A.mk \
    $(LOCAL_DIR)/Z00L.mk \
    $(LOCAL_DIR)/z2_plus.mk \
    $(LOCAL_DIR)/z3c.mk \
    $(LOCAL_DIR)/Z00ED.mk \
    $(LOCAL_DIR)/zl1.mk
