#!/bin/sh

set -e

manifest="$OUT/manifest.xml"
changelog="$OUT/system/etc/Changelog.txt"

# Use 'export USER_BUILD_NO_CHANGELOG=1' before build/envsetup.sh to skip changelog
if [ "$USER_BUILD_NO_CHANGELOG" = "1" ]; then
  echo "Skipped because variable 'USER_BUILD_NO_CHANGELOG' was set to 1" | tee "$changelog"
  exit 0
fi

repo manifest -r > "$manifest.tmp"
# Skip building the changelog if it exists and is up to date
if [ -f "$manifest" -a ! "$manifest" -nt "$changelog" ]; then
  cmp "$manifest" "$manifest.tmp" >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    rm -f "$manifest.tmp"
    echo ${buildppl}"Changelog up to date"${txtrst}
    exit 0
  fi
fi

# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}

rm -f "$manifest"
touch "$changelog"

for i in $(seq 1 10);
do
  after_date=`date --date="$i days ago" +%m-%d-%Y`
  k=$((i - 1))
  until_date=`date --date="$k days ago" +%m-%d-%Y`

  # Line with after --- until was too long for a small ListView
  echo "====================" >> "$changelog"
  echo "     $until_date"     >> "$changelog"
  echo "====================" >> "$changelog"
  echo >> "$changelog"

  # Cycle through every repo to find commits between 2 dates
  current_path="$(realpath `pwd`)"

  repo forall -c "GIT_LOG=\`git log --oneline --after=$after_date --until=$until_date\` ; if [ ! -z \"\$GIT_LOG\" ]; then printf  '\n   * '; realpath \`pwd\` | sed 's|^$current_path/||' ; echo \"\$GIT_LOG\"; fi" >> "$changelog"
  echo >> "$changelog"
done

sed -i 's/^project/   */g' "$changelog"

mv "$manifest.tmp" "$manifest"

exit 0
